name: kasado
description: Basketball court booking app

publish_to: 'none'

version: 0.8.3+11

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Core (state management, data model generation, etc.)
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  freezed_annotation: ^1.1.0
  go_router: ^3.0.1
  # Firebase-related
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  # Google-related
  google_sign_in: ^5.2.3
  # Design
  syncfusion_flutter_calendar: ^19.4.52
  syncfusion_flutter_datagrid: ^19.4.56
  flutter_signin_button: ^2.0.0
  google_fonts: ^2.3.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^9.2.0
  # Utils
  dartz: ^0.10.1
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  uuid: ^3.0.5
  universal_platform: ^1.0.0+1
  time: ^2.1.0
  badges: ^2.0.2
  timeago: ^3.2.2
  qr_flutter: ^4.0.0
  mixpanel_flutter: ^1.4.5
  pub_semver: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
