name: kasado
description: Basketball court booking app

publish_to: 'none'

version: 0.13.2+11

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Core (state management, data model generation, etc.)
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  freezed_annotation: ^1.1.0
  go_router: ^3.0.1
  # Firebase-related
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  geoflutterfire: ^3.0.3
  # Google-related
  google_sign_in: ^5.2.3
  google_place: ^0.4.7
  # Design
  syncfusion_flutter_calendar: ^19.4.52
  syncfusion_flutter_datagrid: ^19.4.56
  sign_button: ^2.0.2
  google_fonts: ^2.3.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^9.2.0
  awesome_dialog: ^2.2.0
  salomon_bottom_bar: ^3.3.0
  google_nav_bar: ^5.0.6
  animated_flip_counter: ^0.2.4
  tab_indicator_styler: ^2.0.0
  lottie: ^1.3.0
  flutter_staggered_animations: ^1.0.0
  # Utils
  dartz: ^0.10.1
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  uuid: ^3.0.5
  universal_platform: ^1.0.0+1
  time: ^2.1.0
  badges: ^2.0.2
  timeago: ^3.2.2
  qr_flutter: ^4.0.0
  mixpanel_flutter: ^1.4.5
  pub_semver: ^2.1.1
  url_launcher: ^6.0.20
  time_range_picker: ^2.1.0
  geolocator: ^8.2.0
  flutter_typeahead: ^3.2.5
  mobile_scanner: ^1.0.0
  algolia: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  dart_code_metrics: ^4.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/lottie/
