// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN3zQFHS9fHxVZEEO_uDoc-xjw_WuDPXU',
    appId: '1:1004868845018:web:a8df7bb2a10b011d4b94e3',
    messagingSenderId: '1004868845018',
    projectId: 'kasado-2022',
    authDomain: 'kasado-2022.firebaseapp.com',
    storageBucket: 'kasado-2022.appspot.com',
    measurementId: 'G-M1K4853CGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQGztFPEa85YtGTVmTkXpdNGR20erwxy0',
    appId: '1:1004868845018:android:130d939394dbc7b44b94e3',
    messagingSenderId: '1004868845018',
    projectId: 'kasado-2022',
    storageBucket: 'kasado-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGqI_UmBXeXlIwo3ErwIYqWe-sKc4jQC8',
    appId: '1:1004868845018:ios:ebce08cd708b29074b94e3',
    messagingSenderId: '1004868845018',
    projectId: 'kasado-2022',
    storageBucket: 'kasado-2022.appspot.com',
    iosClientId: '1004868845018-825ie6eig468e90riqdhtouu91k0gejm.apps.googleusercontent.com',
    iosBundleId: 'com.kasado',
  );
}
